/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {

        mavenCentral()
        maven { url =uri("https://jitpack.io") }
        gradlePluginPortal()

    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        mavenCentral()
        maven { url =uri("https://jitpack.io") }
    }
}

rootProject.name = "kinesis"
include(":app")
include(":core")

