name: CI for Kinesis core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检查出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Java 环境
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # 可以是 'temurin' 或 'zulu'
          java-version: '17'      # 使用的 JDK 版本，根据项目需求调整

      # 设置缓存以加快构建速度
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 构建项目
      - name: Build with Gradle
        run: ./gradlew :core:build --no-daemon

      # 运行测试
      - name: Run tests
        run: ./gradlew :core:test --no-daemon
